# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
name: linux
run-name: Linux Build
"on": [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Development Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/theomund/spinward/devcontainer
          cacheFrom: ghcr.io/theomund/spinward/devcontainer
          push: always
          runCmd: make all
